### ISSUE TITLE
Feature Request - include full chat session URL in notes created during import

### ISSUE THREAD

**Issue by kandyman2017** [Superkikim/nexus-ai-chat-importer#9]
**Description**
When a new note is created via the import, Nexus records the ```conversation_id``` in the YAML, but it would be also useful for a full URL to be generated with ```https://chatgpt.com/c/conversation_id``` within the note itself (outside YAML).

**Use case**
With a clickable URL, the user could easily open the ChatGPT conversation and continue with additional queries from that same session without having to copy/paste the  ```conversation_id``` onto the ```https://chatgpt.com``` part of the URL.

**Comment by Superkikim** [comment]
Hi.

I realize this is missing in the documentation, but you can click the
document title, it will open the conversation in your browser.
Obviously it requires your browser to have a session with your ChatGPT
account. 

Try it. 

I will update the documentation to clarify this point.

**Comment by kandyman2017** [comment]
Yes, it worked! Nice feature.

**Comment by Superkikim** [comment]
Glad you like it. 

Documentation has been updated. Closing this issue.
